### ISSUE TITLE
New Endpoint CreateCourse

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#13]
Payload
```
{
    "CourseDisPlayName": "String", (Intro to System Programming)
    "CourseNameCode": "Number", (5412)
    "Year": "Number",  
    "Term": "string", 
    "Major": "string" 
}
```

**Comment by Kalex123p** [comment]
CreateCourse is done, It is currently sitting on the branch apl0075 pending code review, so you can check it out there. Major being included in the payload is not currently needed but may be needed in the future, this is an ongoing discussion.
