### ISSUE TITLE
New Endpoint GetCourseByMajor

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#14]
Param should be the major name

Response:
![image](https://user-images.githubusercontent.com/66764534/152461088-0382b43a-4ee8-4065-b0a3-a02c666bc4a8.png)

```
{"1": {
  "CourseID" : "primary key",
  "CourseDisPlayName": "FUND OF DB SYSTEMS",
  "CourseNameCode": "4350",
  "Year": "2022",
  "Term": "Fall",
  "Major": "CS"
},"2": {
  "CourseID" : "primary key",
  "CourseDisPlayName": "FUND OF DB SYSTEMS2",
  "CourseNameCode": "4351",
  "Year": "2022",
  "Term": "Fall",
  "Major": "CS"
}}
```

**Comment by Kalex123p** [comment]
GetCourseByMajor is a little more complicated and is not yet ready but it is being worked on, it is a part of an ongoing discussion we wish to have resolved before thursday.

**Comment by Taekwonnie** [comment]
Now that I think about it, params should be major name + semester for easier filter.

**Comment by Kalex123p** [comment]
Currently it takes a string term, int year, and string name, year and term are effectively semester. I need to do some cleanup before finishing connecting the major and course in a join table and it'll be ready.

**Comment by Kalex123p** [comment]
Update: this endpoint is now functional but pending code review, let me know if you encounter any bugs outside of our current issues with error and null checking. Because it has not been reviewed, this endpoint only exists on branch apl0075.
