### ISSUE TITLE
New EndPoint DeleteCourse

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#15]
Not sure what the best way to delete other than the primary key.

**Comment by Kalex123p** [comment]
DeleteCourse is done, It is currently sitting on the branch apl0075 pending code review, so you can check it out there.

**Comment by Taekwonnie** [comment]
The Endpoint is functional, but if I want to delete the CSCE Whatever 3600, the back-end crashes. It seem to only happen to that course specifically.

**Comment by Kalex123p** [comment]
Can you tell me more about the circumstances when this crash happens? is it the only course? are there sections or course outcomes tied to the course?
