### ISSUE TITLE
New Endpoint getCourseOutcomes & getMajorsOutcomes

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#23]
Role:Admin
getCourseOutcomes Return a list of all outcome for a specific course.
getMajorsOutcomes: Return a list of all outcomes for a specific majors.

**Comment by Kalex123p** [comment]
This is done. 
getCourseOutcomes functionality is in endpoint GetMajorOutcomesSatisfied
getMajorsOutcomes is endpoint GetMajorOutcomesByMajor. This is on apl0075 with a pull request into develop.
