### ISSUE TITLE
New endpoint fetch the course list that are assigned to instructor and coordinator.

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#34]
Need an endpoint that return a list of sections assigned to a specific instructor. Role = instructor
Need an endpoint that return a list of courses and sections assigned to a specific coordinator. Role = coordinator

**Comment by bulatzi** [comment]
The GetSectionsByInstructor() endpoint has been added to SectionController.cs

**Comment by Taekwonnie** [comment]
Can you add an endpoint to get section by coordinator. It will query through the courses that are assigned to that instructor, and then find all the sections within that courses.

**Comment by bulatzi** [comment]
Adds the GetCoursesByCoordinator endpoint to the course controller
