### ISSUE TITLE
New endpoint for instructor form

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#37]
For each course's section, the instructor will need to enter statistics such as grades and the percentage of students who scored 75 percent or above on a certain course outcome, save files that demonstrate a specific course outcome, and leave instructor comment (Optional). It should be able to save like a draft and submit (Maybe 2 separate endpoint).

(Role: Instructor)

![image](https://user-images.githubusercontent.com/66764534/159973544-875b21a2-2878-453e-8c88-c9a4de9e8071.png)

**Comment by bulatzi** [comment]
The GradeController and StudentOutcomesCompletedController endpoints have been created. Getters and setters can be used to accomplish draft saving.
