### ISSUE TITLE
Suggestion for EditUser end point

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#6]
Currently, the EditUser endpoint uses the EUID that is passed in to identify the corresponding user in the database and alter their details; as a result, only the first and last name can be changed. Supplying a incorrect, or invalid EUID also crash the whole server rather than returning invalid request. Suggestions:

Old:
```
{
  "firstName": "string",
  "lastName": "string",
  "euid": "string"
}
```
New:
```
{
  "firstName": "string",
  "lastName": "string",
  "euid": "string", //Use to find the user
  "newEuid": "string" //Use to change EUID
}
```

**Comment by Kalex123p** [comment]
Added the ability to edit EUID. null and invalid entry handling is being done this sprint.

**Comment by Taekwonnie** [comment]
https://github.com/bulatzi/segfault-wizards/commit/3e3f7dd9b725254c5a11e2fa2f2bfb0c00db24a3
