### ISSUE TITLE
New Endpoint GetSemesters

### ISSUE THREAD

**Issue by Taekwonnie** [bulatzi/segfault-wizards#8]
Get a list of semesters in the database
Return 
```
"Year": "string",
"Term: "string",
"SemesterID": "string"
```
![unknown](https://user-images.githubusercontent.com/66764534/151859630-e25b7da0-e943-4919-b699-5245cdaee125.png)

**Comment by SeanBoden** [comment]
Created the GetSemesters endpoint.
